import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFExporter } from 'three/addons/exporters/GLTFExporter.js';

const $ = id => document.getElementById(id);
const scene = new THREE.Scene();
scene.background = new THREE.Color(0x0a0d12);
const camera = new THREE.PerspectiveCamera(40,1,.01,100);
camera.position.set(3.2,2.1,5.5);
const renderer = new THREE.WebGLRenderer({antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.shadowMap.enabled = true;
$('viewer').appendChild(renderer.domElement);
const controls = new OrbitControls(camera,renderer.domElement);
controls.enableDamping=true; controls.target.set(0,1.25,0);
scene.add(new THREE.HemisphereLight(0xffffff,0x293342,2.5));
const key = new THREE.DirectionalLight(0xffffff,3); key.position.set(4,6,5); key.castShadow=true; scene.add(key);
const rim = new THREE.DirectionalLight(0x6aa8ff,1.2); rim.position.set(-4,3,-4); scene.add(rim);
const floor = new THREE.Mesh(new THREE.CircleGeometry(2.2,64),new THREE.MeshStandardMaterial({color:0x10151c,roughness:1})); floor.rotation.x=-Math.PI/2; floor.receiveShadow=true; scene.add(floor);
const grid = new THREE.GridHelper(8,20,0x2b3440,0x171c23); grid.position.y=.002; scene.add(grid);

const matBody = new THREE.MeshStandardMaterial({color:0x20252c,roughness:.72,metalness:.05});
const matAccent = new THREE.MeshStandardMaterial({color:0x4d5968,roughness:.72,metalness:.05});
const character = new THREE.Group(); character.name='Character'; scene.add(character);
const rig = new THREE.Group(); rig.name='Skeleton'; character.add(rig);
const bones = {}, meshes=[];
let currentAnim='idle', animating=true, clock=new THREE.Clock();
const defaults={height:1,headScale:1,shoulder:1,torso:1,arms:1,legs:1,hands:1,feet:1};
const params={...defaults};
const loadedMaps={base:null,normal:null,rough:null,metal:null};

const ATLAS={Head:[0,3],Face:[1,3],Torso:[2,3],ChestArmor:[3,3],Pelvis:[0,2],Neck:[1,2],UpperArm_L:[2,2],UpperArm_R:[3,2],LowerArm_L:[0,1],LowerArm_R:[1,1],Hand_L:[2,1],Hand_R:[3,1],Thigh_L:[0,0],Thigh_R:[1,0],Shin_L:[2,0],Shin_R:[3,0],Foot_L:[2,0],Foot_R:[3,0]};
function bone(name,parent,pos=[0,0,0]){const g=new THREE.Group();g.name=name;g.position.set(...pos);(parent||rig).add(g);bones[name]=g;return g}
function applyAtlasUV(geo,name){const uv=geo.getAttribute('uv');if(!uv)return;const [cx,cy]=ATLAS[name]||[0,0],pad=.03,cell=.25,u0=cx*cell+pad*cell,v0=cy*cell+pad*cell,span=cell*(1-pad*2);for(let i=0;i<uv.count;i++)uv.setXY(i,u0+uv.getX(i)*span,v0+uv.getY(i)*span);uv.needsUpdate=true}
function mesh(name,geo,mat,parent,pos=[0,0,0],scale=[1,1,1]){applyAtlasUV(geo,name);const m=new THREE.Mesh(geo,mat);m.name=name;m.position.set(...pos);m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;parent.add(m);meshes.push(m);return m}
function capsule(r,len){return new THREE.CapsuleGeometry(r,len,8,16)}
function box(x,y,z){return new THREE.BoxGeometry(x,y,z,2,2,2)}

function buildCharacter(){while(rig.children.length)rig.remove(rig.children[0]);meshes.length=0;Object.keys(bones).forEach(k=>delete bones[k]);const root=bone('Root',rig,[0,0,0]),hips=bone('Hips',root,[0,1.05,0]),spine=bone('Spine',hips,[0,.38,0]),chest=bone('Chest',spine,[0,.42,0]),neck=bone('Neck',chest,[0,.42,0]),head=bone('Head',neck,[0,.28,0]);const shoulderL=bone('Shoulder_L',chest,[-.46,.28,0]),upperArmL=bone('UpperArm_L',shoulderL,[-.18,0,0]),lowerArmL=bone('LowerArm_L',upperArmL,[-.42,0,0]),handL=bone('Hand_L',lowerArmL,[-.36,0,0]);const shoulderR=bone('Shoulder_R',chest,[.46,.28,0]),upperArmR=bone('UpperArm_R',shoulderR,[.18,0,0]),lowerArmR=bone('LowerArm_R',upperArmR,[.42,0,0]),handR=bone('Hand_R',lowerArmR,[.36,0,0]);const thighL=bone('Thigh_L',hips,[-.2,-.18,0]),shinL=bone('Shin_L',thighL,[0,-.52,0]),footL=bone('Foot_L',shinL,[0,-.48,.08]);const thighR=bone('Thigh_R',hips,[.2,-.18,0]),shinR=bone('Shin_R',thighR,[0,-.52,0]),footR=bone('Foot_R',shinR,[0,-.48,.08]);mesh('Pelvis',capsule(.25,.22),matAccent,hips,[0,.03,0],[1.25,1,1]);mesh('Torso',box(.72,.78,.38),matBody,spine,[0,.35,0]);mesh('ChestArmor',box(.82,.36,.43),matAccent,chest,[0,.08,0]);mesh('Neck',capsule(.09,.12),matBody,neck,[0,.08,0]);mesh('Head',new THREE.SphereGeometry(.24,32,24),matBody,head,[0,.12,0],[.92,1.08,.92]);mesh('Face',box(.27,.13,.025),matAccent,head,[0,.12,.22]);function arm(side,s){const ua=bones['UpperArm_'+side],la=bones['LowerArm_'+side],h=bones['Hand_'+side];mesh('UpperArm_'+side,capsule(.105,.36),matBody,ua,[s*.2,0,0]);meshes.at(-1).rotation.z=Math.PI/2;mesh('LowerArm_'+side,capsule(.09,.31),matAccent,la,[s*.17,0,0]);meshes.at(-1).rotation.z=Math.PI/2;mesh('Hand_'+side,new THREE.SphereGeometry(.11,20,16),matBody,h,[s*.07,0,0],[1.05,.85,.8])}arm('L',-1);arm('R',1);function leg(side){const t=bones['Thigh_'+side],s=bones['Shin_'+side],f=bones['Foot_'+side];mesh('Thigh_'+side,capsule(.14,.43),matBody,t,[0,-.24,0]);mesh('Shin_'+side,capsule(.12,.4),matAccent,s,[0,-.22,0]);mesh('Foot_'+side,box(.25,.16,.42),matBody,f,[0,-.06,.12])}leg('L');leg('R');applyShape();populateBoneUI();updateHierarchy()}
function applyShape(){character.scale.setScalar(params.height);if(bones.Head)bones.Head.scale.setScalar(params.headScale);if(bones.Shoulder_L&&bones.Shoulder_R){bones.Shoulder_L.position.x=-.46*params.shoulder;bones.Shoulder_R.position.x=.46*params.shoulder}const torso=meshes.find(m=>m.name==='Torso'),chest=meshes.find(m=>m.name==='ChestArmor');if(torso)torso.scale.set(params.torso,1,params.torso);if(chest)chest.scale.set(params.torso,1,params.torso);if(bones.LowerArm_L)bones.LowerArm_L.position.x=-.42*params.arms;if(bones.LowerArm_R)bones.LowerArm_R.position.x=.42*params.arms;if(bones.Hand_L)bones.Hand_L.position.x=-.36*params.arms;if(bones.Hand_R)bones.Hand_R.position.x=.36*params.arms;['Hand_L','Hand_R'].forEach(n=>{const m=meshes.find(x=>x.name===n);if(m)m.scale.setScalar(params.hands)});['Thigh_L','Thigh_R','Shin_L','Shin_R'].forEach(n=>{if(bones[n])bones[n].scale.y=params.legs});['Foot_L','Foot_R'].forEach(n=>{const m=meshes.find(x=>x.name===n);if(m)m.scale.set(params.feet,1,params.feet)})}
function resetPose(){Object.values(bones).forEach(b=>b.rotation.set(0,0,0));character.position.set(0,0,0)}
function setRot(name,x=0,y=0,z=0){const b=bones[name];if(b)b.rotation.set(x,y,z)}
function animatePose(t){resetPose();t*=+$('animSpeed').value;if(currentAnim==='idle'){setRot('Chest',0,.03*Math.sin(t*.8),.02*Math.sin(t*.9));character.position.y=.012*Math.sin(t*1.6)}if(currentAnim==='walk'){const a=.65*Math.sin(t*4);setRot('Thigh_L',a);setRot('Thigh_R',-a);setRot('Shin_L',Math.max(0,-a)*.8);setRot('Shin_R',Math.max(0,a)*.8);setRot('Shoulder_L',-a*.55);setRot('Shoulder_R',a*.55)}if(currentAnim==='run'){const a=.95*Math.sin(t*6);setRot('Thigh_L',a);setRot('Thigh_R',-a);setRot('Shin_L',Math.max(0,-a)*1.2);setRot('Shin_R',Math.max(0,a)*1.2);setRot('Shoulder_L',-a*.8);setRot('Shoulder_R',a*.8);setRot('Chest',-.15)}if(currentAnim==='jump'){const p=(Math.sin(t*2)+1)/2;character.position.y=p*.5;setRot('Thigh_L',-.35+p*.65);setRot('Thigh_R',-.35+p*.65);setRot('Shin_L',.55-p*.4);setRot('Shin_R',.55-p*.4)}if(currentAnim==='wave'){setRot('Shoulder_R',0,0,-1.25);setRot('LowerArm_R',0,0,-1.25);setRot('Hand_R',0,0,.4*Math.sin(t*6));setRot('Head',0,.15)}if(currentAnim==='attack'){const p=(Math.sin(t*4)+1)/2;setRot('Shoulder_R',-1.1+p*.9,-.15,-.25);setRot('LowerArm_R',-.8+p*.6);setRot('Chest',0,-.45+p*.9)}}
function resize(){const el=$('viewer'),w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe($('viewer'));addEventListener('resize',resize);(function loop(){requestAnimationFrame(loop);if(animating)animatePose(clock.getElapsedTime());controls.update();renderer.render(scene,camera)})();
function populateBoneUI(){const sel=$('boneSelect');sel.innerHTML='';Object.keys(bones).filter(n=>n!=='Root').forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=n;sel.appendChild(o)});syncBoneControls()}
function syncBoneControls(){const b=bones[$('boneSelect').value];if(!b)return;[['boneX','x'],['boneY','y'],['boneZ','z']].forEach(([id,k])=>{$(id).value=THREE.MathUtils.radToDeg(b.rotation[k]);$(id+'Out').value=Math.round($(id).value)+'°'})}
function updateHierarchy(){$('tree').innerHTML=`<div class="root">▼ Character</div><div class="child">▼ Mesh 3D</div><div class="grand">Head / Torso / Arms / Legs</div><div class="child">▼ Skeleton</div><div class="grand">Root → Hips → Spine → Chest</div><div class="grand">Neck → Head / Arms / Legs</div><div class="child">▼ Materials PBR</div><div class="grand">BaseColor / Normal / Roughness / Metallic</div><div class="child">▼ UV Atlas</div><div class="grand">4 × 4 • layout fixo</div>`;$('meshCount').textContent=meshes.length;$('boneCount').textContent=Object.keys(bones).length}
for(const [id,key,out] of [['height','height','heightOut'],['headScale','headScale','headOut'],['shoulder','shoulder','shoulderOut'],['torso','torso','torsoOut'],['arms','arms','armsOut'],['legs','legs','legsOut'],['hands','hands','handsOut'],['feet','feet','feetOut']]){$(id).addEventListener('input',()=>{params[key]=+$(id).value;$(out).value=(+$(id).value).toFixed(2);applyShape()})}
$('boneSelect').addEventListener('change',()=>{animating=false;syncBoneControls()});for(const [id,axis] of [['boneX','x'],['boneY','y'],['boneZ','z']])$(id).addEventListener('input',()=>{animating=false;const b=bones[$('boneSelect').value];if(b)b.rotation[axis]=THREE.MathUtils.degToRad(+$(''+id).value);$(id+'Out').value=$(''+id).value+'°'});
const helper=new THREE.SkeletonHelper(rig);helper.material.depthTest=false;helper.material.transparent=true;helper.material.opacity=.75;scene.add(helper);$('showBones').addEventListener('change',()=>helper.visible=$('showBones').checked);$('resetPoseBtn').onclick=()=>{animating=false;resetPose();syncBoneControls()};
document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-page').forEach(p=>p.classList.remove('active'));btn.classList.add('active');$('tab-'+btn.dataset.tab).classList.add('active')});document.querySelectorAll('.anim').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.anim').forEach(b=>b.classList.remove('active'));btn.classList.add('active');currentAnim=btn.dataset.anim;animating=true;clock.start()});$('stopAnimBtn').onclick=()=>{animating=false;resetPose()};$('animSpeed').oninput=()=>$('speedOut').value=(+$('animSpeed').value).toFixed(2)+'x';
document.querySelectorAll('[data-preset]').forEach(btn=>btn.onclick=()=>{const p=btn.dataset.preset;const v=p==='hero'?{height:1.08,headScale:.9,shoulder:1.25,torso:1.12,arms:1.05,legs:1.06,hands:1.05,feet:1.08}:p==='stylized'?{height:.94,headScale:1.25,shoulder:.9,torso:.95,arms:.9,legs:.9,hands:1.15,feet:1.15}:p==='slim'?{height:1.05,headScale:.96,shoulder:.88,torso:.82,arms:1.05,legs:1.08,hands:.95,feet:.95}:{...defaults};Object.assign(params,v);for(const [id,key,out] of [['height','height','heightOut'],['headScale','headScale','headOut'],['shoulder','shoulder','shoulderOut'],['torso','torso','torsoOut'],['arms','arms','armsOut'],['legs','legs','legsOut'],['hands','hands','handsOut'],['feet','feet','feetOut']]){$(id).value=params[key];$(out).value=params[key].toFixed(2)}applyShape()});
$('bodyColor').oninput=e=>matBody.color.set(e.target.value);$('accentColor').oninput=e=>matAccent.color.set(e.target.value);$('roughness').oninput=e=>{matBody.roughness=matAccent.roughness=+e.target.value;$('roughOut').value=(+e.target.value).toFixed(2)};$('metalness').oninput=e=>{matBody.metalness=matAccent.metalness=+e.target.value;$('metalOut').value=(+e.target.value).toFixed(2)};
function loadMap(file,type){if(!file)return;const url=URL.createObjectURL(file);new THREE.TextureLoader().load(url,tex=>{tex.colorSpace=type==='base'?THREE.SRGBColorSpace:THREE.NoColorSpace;tex.flipY=false;tex.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());loadedMaps[type]=tex;for(const m of [matBody,matAccent]){if(type==='base')m.map=tex;if(type==='normal')m.normalMap=tex;if(type==='rough')m.roughnessMap=tex;if(type==='metal')m.metalnessMap=tex;m.needsUpdate=true}URL.revokeObjectURL(url);$('textureStatus').textContent='Atlas PBR atualizado: '+type;})}
$('textureInput').onchange=e=>loadMap(e.target.files[0],'base');$('normalInput').onchange=e=>loadMap(e.target.files[0],'normal');$('roughInput').onchange=e=>loadMap(e.target.files[0],'rough');$('metalInput').onchange=e=>loadMap(e.target.files[0],'metal');$('clearTextureBtn').onclick=()=>{for(const t of Object.values(loadedMaps))t?.dispose();Object.keys(loadedMaps).forEach(k=>loadedMaps[k]=null);for(const m of [matBody,matAccent]){m.map=m.normalMap=m.roughnessMap=m.metalnessMap=null;m.needsUpdate=true}$('textureStatus').textContent='Sem atlas aplicado.'};
function uvSvg(){const labels=[['Head',0,3],['Face',1,3],['Torso',2,3],['ChestArmor',3,3],['Pelvis',0,2],['Neck',1,2],['UpperArm_L',2,2],['UpperArm_R',3,2],['LowerArm_L',0,1],['LowerArm_R',1,1],['Hand_L',2,1],['Hand_R',3,1],['Thigh_L',0,0],['Thigh_R',1,0],['Shin_L / Foot_L',2,0],['Shin_R / Foot_R',3,0]];let s=`<svg xmlns="http://www.w3.org/2000/svg" width="2048" height="2048" viewBox="0 0 2048 2048"><rect width="2048" height="2048" fill="#161a20"/>`;for(const [name,x,y] of labels){const px=x*512,py=(3-y)*512;s+=`<rect x="${px+12}" y="${py+12}" width="488" height="488" fill="none" stroke="#8aa4c6" stroke-width="4"/><text x="${px+28}" y="${py+54}" fill="white" font-family="Arial" font-size="34">${name}</text>`}return s+'</svg>'}
$('downloadUvBtn').onclick=()=>{const blob=new Blob([uvSvg()],{type:'image/svg+xml'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='character-forge-uv-template.svg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('testUvBtn').onclick=()=>{const img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(uvSvg());img.onload=()=>{const tex=new THREE.Texture(img);tex.colorSpace=THREE.SRGBColorSpace;tex.flipY=false;tex.needsUpdate=true;for(const m of [matBody,matAccent]){m.map=tex;m.needsUpdate=true}loadedMaps.base=tex;$('textureStatus').textContent='UV de teste aplicado. Cada peça deve cair no bloco correto.'}};
$('frontView').onclick=()=>{camera.position.set(0,1.5,5);controls.target.set(0,1.25,0)};$('sideView').onclick=()=>{camera.position.set(5,1.5,0);controls.target.set(0,1.25,0)};$('backView').onclick=()=>{camera.position.set(0,1.5,-5);controls.target.set(0,1.25,0)};$('resetBtn').onclick=()=>location.reload();$('exportBtn').onclick=()=>{const old=helper.visible;helper.visible=false;new GLTFExporter().parse(character,data=>{const blob=new Blob([data],{type:'model/gltf-binary'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='character-forge.glb';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);helper.visible=old},err=>{console.error(err);helper.visible=old},{binary:true,onlyVisible:true,maxTextureSize:2048})};
buildCharacter();